### ISSUE TITLE
Pagination missing on front page

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Source#40] opened 2024-02-13 01:29 UTC
The Source theme seems to be missing any use of the {{pagination}} helper on the front page.  Because it's making a {{get}} request, it's not possible to navigate to /page/2 and beyond.

**Comment by Sahillather002** [comment] 2024-02-13 01:49
pls assign

**Comment by raad-altaie** [comment] 2024-06-23 18:42
Is this ever going to be fixed?

**Comment by minimaluminium** [comment] 2024-07-16 09:57
Fixed in [1.3.2](https://github.com/TryGhost/Source/commit/61a511b229f3005856dadf625a24d697d5b07986)

**Closed by minimaluminium** 2024-07-16 09:57 UTC

**Comment by minimaluminium** [comment] 2024-07-16 10:01
Lack of pagination on the frontend is by design. Source and a few other official themes (Headline, Episode, Digest, Bulletin) uses `/page/2` as the archive page to list all posts.
